baseURL: 'http://komugi1211s.github.io/'
languageCode: 'ja-jp'
title: 'fuzzy personal website'
theme: 'papermod'

menu:
  main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: = 1

    - identifier: "projects"
      name: "Projects"
      url: "/projects/"
      weight: = 2

    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: = 2

    - identifier: "toys"
      name: "Toys"
      url: "/toys/"
      weight: = 3

params:
  author: "fuzzyperson (komugi1211s)"
  description: "desc"
  copyright: "© fuzzyperson 2020 - present"
  defaultTheme: auto
  ShowCodeCopyButtons: true
  ShowToc: true

  homeInfoParams:
    Title: "Fuzzy page"
    Content: "A place to keep rubbish thoughts. self-taught programmer mainly focusing on C/C++ gamedev. interested in memory management, scripting."

  socialIcons:
    - name: "github"
      url:  "https://github.com/komugi1211s"


markup:
  goldmark:
    renderer:
      unsafe: true
