baseURL: 'https://komugi1211s.github.io/'
languageCode: 'ja-jp'
title: "Fuzzy person's blog"
theme: 'cactus'

menu:
  main:
    - identifier: "about"
      name: "About"
      url: "/about"
      weight: 1

    - identifier: "posts"
      name: "Posts"
      url: "/posts"
      weight: 2

    - identifier: "projects"
      name: "Projects"
      url: "/projects"
      weight: 2

params:
  css:
    - css/portfolio.css

  author: "fuzzyperson (komugi1211s)"
  description: >
    Hello! I am **Soy Fuzzy**, or fuzzyperson. I am a self taught programmer located in Japan.

    for more info about me, please visit [About](/about).

  mainSections: "posts"
  mainSectionTitle: "Posts"
  copyright: "© fuzzyperson 2020 - present"

  social:
    - name: "github"
      link: "https://github.com/komugi1211s"

markup:
  goldmark:
    renderer:
      unsafe: true
